= Código de conducta
:last_updated: 22 Enero de 2024
:permalink: codigo_de_conducta.html
:tags: ["policies"]

== Código de Conducta convenido para Contribuyentes

=== Nuestro compromiso

Nosotros, como miembros, contribuyentes y administradores nos comprometemos a hacer de la participación en nuestra comunidad sea una experiencia libre de acoso para todo el mundo, independientemente de la edad, dimensión corporal, discapacidad visible o invisible, etnicidad, características sexuales, identidad y expresión de género, nivel de experiencia, educación, nivel socio-económico, nacionalidad, apariencia personal, raza, casta, color, religión, o identidad u orientación sexual.

Nos comprometemos a actuar e interactuar de maneras que contribuyan a una comunidad abierta, acogedora, diversa, inclusiva y sana.

=== Nuestros estándares

Ejemplos de comportamientos que contribuyen a crear un ambiente positivo para nuestra comunidad:

* Demostrar empatía y amabilidad ante otras personas
* Respeto a diferentes opiniones, puntos de vista y experiencias
* Dar y aceptar adecuadamente retroalimentación constructiva
* Aceptar la responsabilidad y disculparse ante quienes se vean afectados por nuestros errores, aprendiendo de la experiencia
* Centrarse en lo que sea mejor no sólo para nosotros como individuos, sino para la comunidad en general

Ejemplos de comportamiento inaceptable:

* El uso de lenguaje o imágenes sexualizadas, y aproximaciones o
atenciones sexuales de cualquier tipo
* Comentarios despectivos (_trolling_), insultantes o derogatorios, y ataques personales o políticos
* El acoso en público o privado
* Publicar información privada de otras personas, tales como direcciones físicas o de correo
electrónico, sin su permiso explícito
* Otras conductas que puedan ser razonablemente consideradas como inapropiadas en un
entorno profesional

=== Aplicación de las responsabilidades

Los administradores de la comunidad son responsables de aclarar y hacer cumplir nuestros estándares de comportamiento aceptable y tomarán acciones apropiadas y correctivas de forma justa en respuesta a cualquier comportamiento que consideren inapropiado, amenazante, ofensivo o dañino.

Los administradores de la comunidad tendrán el derecho y la responsabilidad de eliminar, editar o rechazar comentarios, _commits_, código, ediciones de páginas de wiki, _issues_ y otras contribuciones que no se alineen con este Código de Conducta, y comunicarán las razones para sus decisiones de moderación cuando sea apropiado.

=== Alcance

Este código de conducta aplica tanto a espacios del proyecto como a espacios públicos donde un individuo esté en representación del proyecto o comunidad. Ejemplos de esto incluyen el uso de la cuenta oficial de correo electrónico, publicaciones a través de las redes sociales oficiales, o presentaciones con personas designadas en eventos en línea o no.

=== Aplicación

Instancias de comportamiento abusivo, acosador o inaceptable de otro modo podrán ser reportadas a los administradores de la comunidad responsables del cumplimiento a través de coderic@coderic.org Todas las quejas serán evaluadas e investigadas de una manera puntual y justa.

Todos los administradores de la comunidad están obligados a respetar la privacidad y la seguridad de quienes reporten incidentes.

=== Guías de Aplicación

Los administradores de la comunidad seguirán estas Guías de Impacto en la Comunidad para determinar las consecuencias de cualquier acción que juzguen como un incumplimiento de este Código de Conducta:

==== 1. Corrección

*Impacto en la Comunidad*: El uso de lenguaje inapropiado u otro comportamiento considerado no profesional o no acogedor en la comunidad.

*Consecuencia*: Un aviso escrito y privado por parte de los administradores de la comunidad, proporcionando claridad alrededor de la naturaleza de este incumplimiento y una explicación de por qué el comportamiento es inaceptable. Una disculpa pública podría ser solicitada.

==== 2. Aviso

*Impacto en la Comunidad*: Un incumplimiento causado por un único incidente o por una cadena de acciones.

*Consecuencia*: Un aviso con consecuencias por comportamiento prolongado. No se interactúa con las personas involucradas, incluyendo interacción no solicitada con quienes se encuentran aplicando el Código de Conducta, por un periodo especificado de tiempo. Esto incluye evitar las interacciones en espacios de la comunidad, así como a través de canales externos como las redes sociales. Incumplir estos términos puede conducir a una expulsión temporal o permanente.

==== 3. Expulsión temporal  (Baneo)

*Impacto en la Comunidad*: Una serie de incumplimientos de los estándares de la comunidad, incluyendo comportamiento inapropiado continuo.

*Consecuencia*: Una expulsión temporal de cualquier forma de interacción o comunicación pública con la comunidad durante un intervalo de tiempo especificado. No se permite interactuar de manera pública o privada con las personas involucradas, incluyendo interacciones no solicitadas con quienes se encuentran aplicando el Código de Conducta, durante este periodo. Incumplir estos términos puede conducir a una expulsión permanente.

==== 4. Expulsión permanente  (Betado, Expulsión y Bloqueo)

*Impacto en la Comunidad*: Demostrar un patrón sistemático de incumplimientos de los estándares de la comunidad, incluyendo conductas inapropiadas prolongadas en el tiempo, acoso de individuos, o agresiones o menosprecio a grupos de individuos.

*Consecuencia*: Una expulsión permanente de cualquier tipo de interacción pública con la comunidad del proyecto.

=== Atribución

Este Código de Conducta es una adaptación del https://www.contributor-covenant.org[Contributor Covenant], versión 2.1,
disponible en https://www.contributor-covenant.org/es/version/2/1/code_of_conduct.html

Las Guías de Impacto en la Comunidad están inspiradas en la https://github.com/mozilla/diversity[escalera de aplicación del código de conducta de Mozilla].

Para respuestas a las preguntas frecuentes de este código de conducta, consulta las FAQ en
https://www.contributor-covenant.org/faq. Hay traducciones disponibles en https://www.contributor-covenant.org/translations

== Código de Conducta Ciudadana

=== 1. Propósito

Un objetivo principal del nombre de la comunidad es incluir al mayor número de contribuyentes, con los antecedentes más variados y diversos posibles. Como tal, estamos comprometidos a brindar un ambiente amigable, seguro y acogedor para todos, independientemente de su género, orientación sexual, capacidad, origen étnico, nivel socioeconómico y religión (o la falta de ella).

Este código de conducta describe nuestras expectativas para todos aquellos que participan en nuestra comunidad, así como las consecuencias del comportamiento inaceptable.

Invitamos a todos aquellos que participan en Nombre de la comunidad a ayudarnos a crear experiencias seguras y positivas para todos.

=== 2. Ciudadanía abierta [fuente/cultura/tecnología]

Un objetivo complementario de este Código de conducta es aumentar la ciudadanía abierta [fuente/cultura/tecnología] alentando a los participantes a reconocer y fortalecer las relaciones entre nuestras acciones y sus efectos en nuestra comunidad.

Las comunidades reflejan las sociedades en las que existen y la acción positiva es esencial para contrarrestar las muchas formas de desigualdad y abusos de poder que existen en la sociedad.

Si ve a alguien que está haciendo un esfuerzo adicional para garantizar que nuestra comunidad sea acogedora, amigable y aliente a todos los participantes a contribuir al máximo, queremos saberlo.

=== 3. Comportamiento esperado

The following behaviors are expected and requested of all community members:

* Participa de forma auténtica y activa. Al hacerlo, contribuye a la salud y la longevidad de esta comunidad.
* Ejerza consideración y respeto en su discurso y acciones.
* Intente la colaboración antes del conflicto.
* Abstenerse de comportamientos y expresiones degradantes, discriminatorias o acosadoras.
* Sea consciente de su entorno y de sus compañeros participantes. Alerte a los líderes comunitarios si nota una situación peligrosa, alguien en peligro o violaciones de este Código de conducta, incluso si parecen intrascendentes.
* Recuerde que los lugares para eventos comunitarios pueden compartirse con miembros del público; Sea respetuoso con todos los clientes de estos lugares.

=== 4. Comportamiento inaceptable

Los siguientes comportamientos se consideran acoso y son inaceptables dentro de nuestra comunidad:

* Violencia, amenazas de violencia o lenguaje violento dirigido contra otra persona.
* Chistes y lenguaje sexistas, racistas, homofóbicos, transfóbicos, capacitistas o discriminatorios.
* Publicar o mostrar material sexualmente explícito o violento.
* Publicar o amenazar con publicar información de identificación personal de otras personas ("doxing").
* Insultos personales, particularmente aquellos relacionados con género, orientación sexual, raza, religión o discapacidad.
* Fotografía o grabación inapropiada.
* Contacto físico inadecuado. Debes tener el consentimiento de alguien antes de tocarlo.
* Atención sexual no deseada. Esto incluye comentarios o chistes sexualizados; tocamientos inapropiados, manoseos e insinuaciones sexuales no deseadas.
* Intimidación, acecho o seguimiento deliberado (en línea o en persona).
* Defender o fomentar cualquiera de los comportamientos anteriores.
* Interrupción sostenida de eventos comunitarios, incluidas charlas y presentaciones.

=== 5. Política de armas

No se permitirán armas en eventos de nombres de la comunidad, espacios comunitarios ni en otros espacios cubiertos por el alcance de este Código de conducta. Las armas incluyen, entre otras, pistolas, explosivos (incluidos fuegos artificiales) y cuchillos grandes, como los que se utilizan para cazar o exhibir, así como cualquier otro artículo utilizado con el fin de causar lesiones o daño a otros. A cualquier persona que sea vista en posesión de uno de estos artículos se le pedirá que se vaya inmediatamente y solo se le permitirá regresar sin el arma. Además, se espera que los miembros de la comunidad cumplan con todas las leyes estatales y locales sobre este asunto.

=== 6. Consecuencias del comportamiento inaceptable

No se tolerará el comportamiento inaceptable de ningún miembro de la comunidad, incluidos los patrocinadores y aquellos con autoridad para tomar decisiones.

Se espera que cualquier persona a la que se le solicite detener un comportamiento inaceptable cumpla de inmediato.

Si un miembro de la comunidad tiene un comportamiento inaceptable, los organizadores de la comunidad pueden tomar cualquier medida que consideren apropiada, que puede incluir una prohibición temporal o la expulsión permanente de la comunidad sin previo aviso (y sin reembolso en el caso de un evento pago).

=== 7. Directrices para la presentación de informes y quejas

Si está sujeto o es testigo de un comportamiento inaceptable, o tiene alguna otra inquietud, notifique a un organizador comunitario lo antes posible. admin@coderic.org.

http://coderic.org/reporting[Reporting guidelines]

Además, los organizadores comunitarios están disponibles para ayudar a los miembros de la comunidad a interactuar con las autoridades locales o para ayudar a quienes experimentan un comportamiento inaceptable a sentirse seguros. En el contexto de eventos presenciales, los organizadores también proporcionarán acompañantes según lo desee la persona que sufre la angustia.

=== 8. Abordar las quejas

Si cree que ha sido acusado falsa o injustamente de violar este Código de conducta, debe notificar nuestro comité disciplinario con una descripción concisa de su queja. Su queja se manejará de acuerdo con nuestras políticas vigentes. http://coderic.org/policy[Policy]

=== 9. Alcance

Esperamos que todos los participantes de la comunidad (contribuyentes, remunerados o no, patrocinadores y otros invitados) respeten este Código de conducta en todos los lugares de la comunidad, en línea y en persona, así como en todas las comunicaciones individuales relacionadas con a los negocios comunitarios.

Este código de conducta y sus procedimientos relacionados también se aplican al comportamiento inaceptable que ocurre fuera del alcance de las actividades de la comunidad cuando dicho comportamiento tiene el potencial de afectar negativamente la seguridad y el bienestar de los miembros de la comunidad.

=== 10. Información de contacto

admin@coderic.org

=== 11. Licencia y atribución

El Código de Conducta Ciudadana es distribuido por http://stumptownsyndicate.org[Stumptown Syndicate] bajo una http://creativecommons.org/licenses/by-sa/3.0/[Licencia Creative Commons Attribution-ShareAlike].

Partes del texto derivadas del https://www.djangoproject.com/conduct/[Código de conducta de Django] y la http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy[Política antiacoso del feminismo geek].

_Revision 2.3. Posted 6 March 2017._

_Revision 2.2. Posted 4 February 2016._

_Revision 2.1. Posted 23 June 2014._

_Revision 2.0, adopted by the http://stumptownsyndicate.org[Stumptown Syndicate] board on 10 January 2013. Posted 17 March 2013._
