site:
  title: Coderic Documentación
  start_page: ROOT::index.adoc
  robots: disallow
content:
  sources: 
  - url: .
    branches: HEAD
  - url: https://github.com/CodericLatam/Prodaric.git
    branches: gh-pages
    start_path: docs
  - url: https://github.com/CodericLatam/Protejo.git
    branches: HEAD
    start_path: docs
ui: 
  bundle:
    url: https://codericlatam.github.io/coderic-theme-docs/ui-bundle.zip
    snapshot: true
